version: "2"

volumes:
  rails-template-sync:
    external: true
  gem_store_rails_template:
    external: true
  db_data_rails_template:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data_rails_template:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bundle exec rails start
    env_file:
      - .env.docker
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - gem_store_rails_template:/bundle
      - .:/rails_template
      - rails-template-sync:/rails_template:nocopy
