version: '3'

services:

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data_rails_template:/var/lib/postgresql/data:cached
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - internal

  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bundle exec rails start
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - gem_store_rails_template:/bundle:cached
      - .:/rails_template:cached
    networks:
      - internal
      - external

  sidekiq:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - gem_store_rails_template:/bundle:cached
      - .:/rails_template:cached
    networks:
      - internal

volumes:

  gem_store_rails_template:
    external: true

  db_data_rails_template:

networks:
  internal:
  external:

